[package]
name = "rust_gpio"
version = "0.1.0"
authors = ["kawamataryou <ba068082@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.12.0"

